In [1]:
import pandas as pd
import censusdata
import numpy as np
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.precision', 2)
import statsmodels.formula.api as sm

from scipy import stats
import plotly.express as px         # plotting

from sodapy import Socrata             # NYC Open Data

from urllib.request import urlopen     # Turnign long an dlat to census geoids                                                  # Getting the json data from the url
import requests

crimeFile = "NYPD_Complaint_Data_Historic_2010_2011.csv"
crimeOutFile = "NYPD_Complaint_Data_Historic_WITH_CENSUS_DATA_100k200k_2.csv"
crimeDF = pd.read_csv(crimeFile)
crimeDF

        CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                        OFNS_DESC  PD_CD  ... SUSP_SEX TRANSIT_DISTRICT Latitude Longitude                        Lat_Lon               PATROL_BORO STATION_NAME  VIC_AGE_GROUP                  VIC_RACE VIC_SEX
0        279329041   12/31/2011  01:55:00 PM          NaN          NaN         32.0  12/31/2011    101  MURDER & NON-NEGL. MANSLAUGHTER    NaN  ...      NaN              NaN    40.82    -73.94   (40.822403275, -73.94295804)                       NaN          NaN        UNKNOWN                     BLACK       M
1        859362619   12/31/2011  01:45:00 AM   12/31/2011  01:50:00 AM        102.0  12/31/2011    348         VEHICLE AND TRAFFIC LAWS  916.0  ...      NaN              NaN    40.69    -73.82  (40.690256543, -73.824962482)  PATROL BORO QUEENS SOUTH          NaN          25-44  ASIAN / PACIFIC ISLANDER       M
2        944834875   12/31/2011  03:30:00 AM          NaN          NaN         72.0  12/31/2011    114                            ARSON  263.0  ...      NaN              NaN    40.65    -74.02    (40.64526601, -74.02271787)   PATROL BORO BKLYN SOUTH          NaN            NaN                   UNKNOWN       D
3        678955670   12/31/2011  03:30:00 AM   12/31/2011  03:40:00 AM        103.0  12/31/2011    105                          ROBBERY  397.0  ...        M              NaN    40.69    -73.80    (40.6928541, -73.803477885)  PATROL BORO QUEENS SOUTH          NaN          25-44                     WHITE       M
4        360013845   12/31/2011  10:10:00 AM   12/31/2011  10:30:00 AM        113.0  12/31/2011    578                    HARRASSMENT 2  638.0  ...        M              NaN    40.69    -73.77  (40.685494894, -73.774769525)  PATROL BORO QUEENS SOUTH          NaN          25-44                     BLACK       F
...            ...          ...          ...          ...          ...          ...         ...    ...                              ...    ...  ...      ...              ...      ...       ...                            ...                       ...          ...            ...                       ...     ...
311587   999306278   01/01/2010  12:00:00 PM   03/12/2010  09:20:00 AM        102.0  03/12/2010    361    OFF. AGNST PUB ORD SENSBLTY &  639.0  ...        F              NaN    40.69    -73.84   (40.693045553, -73.83637202)  PATROL BORO QUEENS SOUTH          NaN          18-24            WHITE HISPANIC       F
311588   682302619   01/01/2010  04:10:00 AM          NaN          NaN         70.0  01/01/2010    341                    PETIT LARCENY  338.0  ...      NaN              NaN    40.64    -73.96    (40.641890937, -73.9606821)   PATROL BORO BKLYN SOUTH          NaN          18-24                     BLACK       F
311589   168507284   01/01/2010  12:01:00 AM          NaN          NaN         72.0  12/05/2011    233                       SEX CRIMES  175.0  ...        M              NaN    40.66    -74.00  (40.658193432, -74.001032243)   PATROL BORO BKLYN SOUTH          NaN            <18            WHITE HISPANIC       F
311590   212572104   01/01/2010  09:00:00 PM   01/01/2010  11:20:00 PM         41.0  01/02/2010    361    OFF. AGNST PUB ORD SENSBLTY &  639.0  ...        M              NaN    40.82    -73.90  (40.819028122, -73.899898721)         PATROL BORO BRONX          NaN          25-44                     BLACK       F
311591   763452030   01/01/2010  04:20:00 AM   01/01/2010  04:30:00 AM         10.0  01/01/2010    105                          ROBBERY  392.0  ...        F              NaN    40.75    -74.00  (40.746827406, -74.001087754)     PATROL BORO MAN SOUTH          NaN          25-44                   UNKNOWN       M

[311592 rows x 35 columns]

In [2]:
crimeDF = crimeDF[100000:200001]
crimeDF = crimeDF.reset_index(drop=True) 
crimeDF

   CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                        OFNS_DESC  PD_CD  ... SUSP_SEX TRANSIT_DISTRICT Latitude Longitude                        Lat_Lon                PATROL_BORO STATION_NAME  VIC_AGE_GROUP                  VIC_RACE VIC_SEX
0   279329041   12/31/2011  01:55:00 PM          NaN          NaN         32.0  12/31/2011    101  MURDER & NON-NEGL. MANSLAUGHTER    NaN  ...      NaN              NaN    40.82    -73.94   (40.822403275, -73.94295804)                        NaN          NaN        UNKNOWN                     BLACK       M
1   859362619   12/31/2011  01:45:00 AM   12/31/2011  01:50:00 AM        102.0  12/31/2011    348         VEHICLE AND TRAFFIC LAWS  916.0  ...      NaN              NaN    40.69    -73.82  (40.690256543, -73.824962482)   PATROL BORO QUEENS SOUTH          NaN          25-44  ASIAN / PACIFIC ISLANDER       M
2   944834875   12/31/2011  03:30:00 AM          NaN          NaN         72.0  12/31/2011    114                            ARSON  263.0  ...      NaN              NaN    40.65    -74.02    (40.64526601, -74.02271787)    PATROL BORO BKLYN SOUTH          NaN            NaN                   UNKNOWN       D
3   678955670   12/31/2011  03:30:00 AM   12/31/2011  03:40:00 AM        103.0  12/31/2011    105                          ROBBERY  397.0  ...        M              NaN    40.69    -73.80    (40.6928541, -73.803477885)   PATROL BORO QUEENS SOUTH          NaN          25-44                     WHITE       M
4   360013845   12/31/2011  10:10:00 AM   12/31/2011  10:30:00 AM        113.0  12/31/2011    578                    HARRASSMENT 2  638.0  ...        M              NaN    40.69    -73.77  (40.685494894, -73.774769525)   PATROL BORO QUEENS SOUTH          NaN          25-44                     BLACK       F
5   426783060   12/31/2011  05:04:00 PM   12/31/2011  05:15:00 PM        120.0  12/31/2011    675              ADMINISTRATIVE CODE  858.0  ...      NaN              NaN    40.61    -74.08  (40.614624398, -74.084716734)  PATROL BORO STATEN ISLAND          NaN            NaN                   UNKNOWN       E
6   841981340   12/31/2011  01:00:00 AM          NaN          NaN        104.0  12/31/2011    351   CRIMINAL MISCHIEF & RELATED OF  258.0  ...      NaN              NaN    40.70    -73.90   (40.696101475, -73.89631115)   PATROL BORO QUEENS NORTH          NaN            NaN                   UNKNOWN       E
7   989679721   12/31/2011  07:55:00 PM   12/31/2011  08:00:00 PM        113.0  12/31/2011    106                   FELONY ASSAULT  109.0  ...        F              NaN    40.67    -73.77  (40.668108463, -73.768747038)   PATROL BORO QUEENS SOUTH          NaN          25-44  ASIAN / PACIFIC ISLANDER       F
8   609073409   12/31/2011  08:30:00 PM   12/31/2011  08:32:00 PM         25.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...      NaN              NaN    40.79    -73.93  (40.787874599, -73.928181646)      PATROL BORO MAN NORTH          NaN          45-64                     BLACK       M
9   324614519   12/31/2011  06:00:00 AM   12/31/2011  06:05:00 AM        120.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...        U              NaN    40.62    -74.08  (40.616953781, -74.082241537)  PATROL BORO STATEN ISLAND          NaN          25-44                     BLACK       M

[10 rows x 35 columns]

In [3]:
# 1) Appending New Cols - Cols for census data:
crimeDF["Geoid"] = int
crimeDF["Date"]  = str         #rpt_dt
crimeDF["Month"] = int
crimeDF["Year"]  = int
crimeDF["CrimeComplaint"] = str
crimeDF["CountyName"]     = str 
crimeDF["CensusTract_2010_NAME"] = str  
censusCols = ["CountyName", "Geoid", "CensusTract_2010_NAME"]
crimeDF

   CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                        OFNS_DESC  PD_CD  ... VIC_AGE_GROUP                  VIC_RACE VIC_SEX          Geoid           Date          Month           Year  CrimeComplaint     CountyName CensusTract_2010_NAME
0   279329041   12/31/2011  01:55:00 PM          NaN          NaN         32.0  12/31/2011    101  MURDER & NON-NEGL. MANSLAUGHTER    NaN  ...       UNKNOWN                     BLACK       M  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
1   859362619   12/31/2011  01:45:00 AM   12/31/2011  01:50:00 AM        102.0  12/31/2011    348         VEHICLE AND TRAFFIC LAWS  916.0  ...         25-44  ASIAN / PACIFIC ISLANDER       M  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
2   944834875   12/31/2011  03:30:00 AM          NaN          NaN         72.0  12/31/2011    114                            ARSON  263.0  ...           NaN                   UNKNOWN       D  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
3   678955670   12/31/2011  03:30:00 AM   12/31/2011  03:40:00 AM        103.0  12/31/2011    105                          ROBBERY  397.0  ...         25-44                     WHITE       M  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
4   360013845   12/31/2011  10:10:00 AM   12/31/2011  10:30:00 AM        113.0  12/31/2011    578                    HARRASSMENT 2  638.0  ...         25-44                     BLACK       F  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
5   426783060   12/31/2011  05:04:00 PM   12/31/2011  05:15:00 PM        120.0  12/31/2011    675              ADMINISTRATIVE CODE  858.0  ...           NaN                   UNKNOWN       E  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
6   841981340   12/31/2011  01:00:00 AM          NaN          NaN        104.0  12/31/2011    351   CRIMINAL MISCHIEF & RELATED OF  258.0  ...           NaN                   UNKNOWN       E  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
7   989679721   12/31/2011  07:55:00 PM   12/31/2011  08:00:00 PM        113.0  12/31/2011    106                   FELONY ASSAULT  109.0  ...         25-44  ASIAN / PACIFIC ISLANDER       F  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
8   609073409   12/31/2011  08:30:00 PM   12/31/2011  08:32:00 PM         25.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...         45-64                     BLACK       M  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>
9   324614519   12/31/2011  06:00:00 AM   12/31/2011  06:05:00 AM        120.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...         25-44                     BLACK       M  <class 'int'>  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  <class 'str'>         <class 'str'>

[10 rows x 42 columns]

In [5]:
# 2) Func
def getCensusTract(longitude, latitude, retryRun=0):                                                                 # returns an array [censusTract, CensusBlock, CountyName]
    url = "https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x={0}&y={1}&benchmark=Public_AR_Census2010&vintage=Census2010_Census2010&format=json".format(longitude,latitude)
    if retryRun == 11:                                                                                              # Failed to get json data 11 times with this longitude and latitude so need to skip this one
        print("*****Failed 11 times to get geodata so will insert 'error'*****")
        return [str("error"), str("error"), str("error")]
    try:
        response = requests.get(url)
        dataJSON = response.json()
        data    = dataJSON["result"]
        countyNAME    = data["geographies"]["Counties"][0]["NAME"] 
        GEOID =  data["geographies"]["Census Tracts"][0]["GEOID"]
        tractNAME     = data["geographies"]["Census Tracts"][0]["NAME"]
        return [
            str(countyNAME), 
            str(GEOID), 
            str(tractNAME)
        ]
    except:
        retryRun+=1
        print("_____Error on longitude, latitude: "+str(longitude)+","+str(latitude) + ".....retrying... "+str(retryRun))
        return getCensusTract(longitude, latitude,retryRun)                                                         # need to return the recursive function
    return

# 3) Using Long and Lat to populate the Census Data Cols
print("...Getting Census Information of Crime Reports from Longitude and Latitude Coordinates...\n...Should take some a long time...")
rowsToDel = []
for row in range(0,len(crimeDF)):
    retryRun = 0
    lat = float(crimeDF.iloc[row]["Latitude"])
    lon = float(crimeDF.iloc[row]["Longitude"])
    if np.isnan(lon) or np.isnan(lat):
        print("***This report has no Longitude and Latitude Data so will skip it and delete it from the df***")
        rowsToDel.append(row)
        continue
    
    returnArray = getCensusTract(lon, lat)            
    if len(censusCols) == len(returnArray):
        for i in range(0, len(censusCols)):
            crimeDF.at[row, censusCols[i]] = returnArray[i] 
    else:
        print("*** Number of col to add and values to polulate cols are not the same!! ******") 
    if row%1000 == 0:
        print(row)
        crimeDF.to_csv(crimeOutFile, index=False)   # Saving just in case 
crimeDF.to_csv(crimeOutFile, index=False)   # Saving just in case 
print("DONE")
crimeDF

...Getting Census Information of Crime Reports from Longitude and Latitude Coordinates...
...Should take some a long time...
0
DONE

   CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                        OFNS_DESC  PD_CD  ... VIC_AGE_GROUP                  VIC_RACE VIC_SEX        Geoid           Date          Month           Year  CrimeComplaint       CountyName CensusTract_2010_NAME
0   279329041   12/31/2011  01:55:00 PM          NaN          NaN         32.0  12/31/2011    101  MURDER & NON-NEGL. MANSLAUGHTER    NaN  ...       UNKNOWN                     BLACK       M  36061025900  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  New York County      Census Tract 259
1   859362619   12/31/2011  01:45:00 AM   12/31/2011  01:50:00 AM        102.0  12/31/2011    348         VEHICLE AND TRAFFIC LAWS  916.0  ...         25-44  ASIAN / PACIFIC ISLANDER       M  36081015400  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>    Queens County      Census Tract 154
2   944834875   12/31/2011  03:30:00 AM          NaN          NaN         72.0  12/31/2011    114                            ARSON  263.0  ...           NaN                   UNKNOWN       D  36047002200  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>     Kings County       Census Tract 22
3   678955670   12/31/2011  03:30:00 AM   12/31/2011  03:40:00 AM        103.0  12/31/2011    105                          ROBBERY  397.0  ...         25-44                     WHITE       M  36081019800  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>    Queens County      Census Tract 198
4   360013845   12/31/2011  10:10:00 AM   12/31/2011  10:30:00 AM        113.0  12/31/2011    578                    HARRASSMENT 2  638.0  ...         25-44                     BLACK       F  36081028200  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>    Queens County      Census Tract 282
5   426783060   12/31/2011  05:04:00 PM   12/31/2011  05:15:00 PM        120.0  12/31/2011    675              ADMINISTRATIVE CODE  858.0  ...           NaN                   UNKNOWN       E  36085004000  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  Richmond County       Census Tract 40
6   841981340   12/31/2011  01:00:00 AM          NaN          NaN        104.0  12/31/2011    351   CRIMINAL MISCHIEF & RELATED OF  258.0  ...           NaN                   UNKNOWN       E  36081056700  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>    Queens County      Census Tract 567
7   989679721   12/31/2011  07:55:00 PM   12/31/2011  08:00:00 PM        113.0  12/31/2011    106                   FELONY ASSAULT  109.0  ...         25-44  ASIAN / PACIFIC ISLANDER       F  36081033000  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>    Queens County      Census Tract 330
8   609073409   12/31/2011  08:30:00 PM   12/31/2011  08:32:00 PM         25.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...         45-64                     BLACK       M  36061024000  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  New York County      Census Tract 240
9   324614519   12/31/2011  06:00:00 AM   12/31/2011  06:05:00 AM        120.0  12/31/2011    344     ASSAULT 3 & RELATED OFFENSES  101.0  ...         25-44                     BLACK       M  36085002900  <class 'str'>  <class 'int'>  <class 'int'>   <class 'str'>  Richmond County       Census Tract 29

[10 rows x 42 columns]